#+TITLE: Bashrc
#+AUTHOR: seamus tuohy
#+EMAIL: s2e@seamustuohy.com
#+DATE: 2015 Apr 18
#+TAGS: bash commandline

* Mobile Home

I keep my home directory mobile so that I can easily switch between computers.

#+BEGIN_SRC sh
export MOBILE_HOME=/media/truecrypt1
#+END_SRC

* Editor

# ~/.bashrc: executed by bash(1) for non-login shells.
  # see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

set default editor to emacs
#+BEGIN_SRC sh
export EDITOR=emacs
#+END_SRC

If not running interactively, don't do anything
#+BEGIN_SRC sh
case $- in
    *i*) ;;
      *) return;;
esac
#+END_SRC

* History

#==================================
#        HISTORY CONTROLS
#==================================

Huge history. Doesn't appear to slow things down, so why not?
for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
#+BEGIN_SRC sh
HISTSIZE=500000
HISTFILESIZE=100000
#+END_SRC

Don't put duplicate lines or lines starting with space in the history.
See bash(1) for more options
#+BEGIN_SRC sh
HISTCONTROL=ignoreboth
#+END_SRC

Append to the history file, don't overwrite it
#+BEGIN_SRC sh
shopt -s histappend
#+END_SRC

ALSO See: PROMPT_COMMAND below

Don't record some commands
#+BEGIN_SRC sh
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"
#+END_SRC

remove duplicates while preserving input order
#+BEGIN_SRC sh
function dedup {
   awk '! x[$0]++' $@
}
#+END_SRC

 removes $HISTIGNORE commands from input
#+BEGIN_SRC sh
function remove_histignore {
   if [ -n "$HISTIGNORE" ]; then
      # replace : with |, then * with .*
      local IGNORE_PAT=`echo "$HISTIGNORE" | sed s/\:/\|/g | sed s/\*/\.\*/g`
      # negated grep removes matches
      grep -vx "$IGNORE_PAT" $@
   else
      cat $@
   fi
}
#+END_SRC

 clean up the history file by remove duplicates and commands matching $HISTIGNORE entries
#+BEGIN_SRC sh
function history_cleanup {
   local HISTFILE_SRC=~/.bash_history
   local HISTFILE_DST=/tmp/.$USER.bash_history.clean
   if [ -f $HISTFILE_SRC ]; then
      \cp $HISTFILE_SRC $HISTFILE_SRC.backup
      dedup $HISTFILE_SRC | remove_histignore >| $HISTFILE_DST
      \mv $HISTFILE_DST $HISTFILE_SRC
      chmod go-r $HISTFILE_SRC
      history -c
      history -r
   fi
}
#+END_SRC

#run histroy cleanup on bash startup

#+BEGIN_SRC sh
history_cleanup
#+END_SRC


#==============================

* Colors

#+BEGIN_SRC sh
export TERM=xterm-color
export CLICOLOR=1
#+END_SRC


Colorize basic commands
#+BEGIN_SRC sh
  alias ls="ls --color=auto"
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
#+END_SRC

* Prompt

#+BEGIN_SRC sh
PS1="\[\e[32m\]\$(parse_git_branch)\[\e[34m\]\h:\W \$ \[\e[m\]"
#+END_SRC

..fix tangle errors..

#+BEGIN_SRC sh
PROMPT_COMMAND=prompt_commands
#+END_SRC

Add additional prompt commands to the function below
  - update histfile after every command

#+BEGIN_SRC sh
prompt_commands() {
        history -a
}
#+END_SRC

* Display

Check the window size after each command and, if necessary, update the values of LINES and COLUMNS.
#+BEGIN_SRC sh
shopt -s checkwinsize
#+END_SRC

* Completion

If set, the pattern "**" used in a pathname expansion context will match all files and zero or more directories and subdirectories.
#+BEGIN_SRC sh
shopt -s globstar
#+END_SRC

Enable programmable completion features (you don't need to enable this, if it's already enabled in /etc/bash.bashrc and /etc/profile sources /etc/bash.bashrc).

#+BEGIN_SRC sh
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
#+END_SRC

Perform file completion in a case insensitive fashion
#+BEGIN_SRC sh
bind "set completion-ignore-case on"
#+END_SRC

Treat hyphens and underscores as equivalent
#+BEGIN_SRC sh
bind "set completion-map-case on"
#+END_SRC

Display matches for ambiguous patterns at first tab press
#+BEGIN_SRC sh
bind "set show-all-if-ambiguous on"
#+END_SRC

* Load External

** Alias
#+BEGIN_SRC sh
if [ -f ~/.bin/bash_alias ]; then
    source ~/.bin/bash_alias
fi
#+END_SRC

* PATH
Add CASK to the path for emacs.
#+BEGIN_SRC sh
export PATH="$PATH:$HOME/.cask/bin"
#+END_SRC

Things
#+BEGIN_SRC sh
export PATH="$PATH:$HOME/.cabal/bin"
#+END_SRC


* Technical Section
This file originally came from an [[http://orgmode.org][org-mode]] file.
Create the script by tangling it with: =C-c C-v t=

#+PROPERTY: tangle ~/.bashrc
#+PROPERTY: comments org
#+PROPERTY: shebang #!/usr/bin/env bash
#+DESCRIPTION: My BashRC file
